### PR TITLE
Resource manager - Add resource and group

### PR DESCRIPTION
**Pull request by Compro-Prasad**

### CODE REVIEW

**Comment by joesteeve** [comment]
@Compro-Prasad : Run it on the entire code base.

**Comment by Compro-Prasad** [comment]
But it will produce large diffs no?

**Comment by joesteeve** [comment]
Thats alright. Its one single changeset.

**Comment by Compro-Prasad** [comment]
Actually `sh format-code.sh` is designed to format just the files that are changed and being tracked by `git`.

**Comment by joesteeve** [comment]
Discuss on ML

**Pull request merged**
